[workspace]
resolver = "3"
members = [
  "polydrome", 
  "polydrome-subsonic"
]

[workspace.dependencies]
quick-xml = { version = "0.38", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }